### ISSUE TITLE
Add integration tests.

### ISSUE THREAD

**Issue by sharkinsspatial** [developmentseed/eoapi-cdk#13]
Initial deployment of this construct revealed several small CDK and configuration related issues that made the resulting infrastructure fail when used in a stack.  ref https://github.com/developmentseed/cdk-pgstac/commit/be40af70326f04d7ed9583569ad49f12da416d6f and ref https://github.com/developmentseed/cdk-pgstac/pull/8

We should build an integration test suite which deploys an ephemeral stack using the construct, it should

- Create a collection via the Ingestor API.
- Ingest an item via the Ingestor API.
- Verify the creation of the item via the STAC API endpoint.

Given the expense (in deployment time and resources) these integration tests should likely only run against new release tags.
```[tasklist]
### Tasks
- [ ] https://github.com/developmentseed/cdk-pgstac/issues/47
- [x] Create a test suite : https://github.com/developmentseed/eoapi-tests
- [x] Create a github action that runs the demo deployment, runs the tests on it, and tears down the deployment
```

**Comment by emileten** [comment]
We would like to see this implemented since we use `cdk-pgstac` to deploy the MAAP data system. 

I am wondering if, now that we also have a titiler-pgstac endpoint, we also want to add an item such as this one in your list @sharkinsspatial :  

- create a mosaic with the deployed titiler endpoint
- verify the creation of that mosaic through the titiler APIs

**Comment by emileten** [comment]
Other suggestion : because it takes a significant time to deploy a complete app with all these constructs, and even longer to destroy all the resources after the fact, I've been exploring [LocalStack](https://github.com/localstack) to test the deployment 'locally'. To test whether `localstack` is able to emulate all the services we use, I've been trying to deploy [maap-cdk-pgstac](https://github.com/MAAP-Project/maap-cdk-pgstac) out of the box with it. Although I still have a couple bugs to resolve to complete my attempt, it works better than what I expected and it's an order of magnitude faster than a real deployment.

So, assuming : 

1. a `localstack` deployment can be used to actually try to publish and query collections (I don't know about that yet).
2. we manage to use their `pro` version (which we need), either by using the credits they provide to open source repos or actually getting a membership.

What do people think of that, rather than doing a full real deployment and then tear it down ? @alukach, thoughts ?
