### ISSUE TITLE
Add a vector application construct

### ISSUE THREAD

**Issue by emileten** [developmentseed/eoapi-cdk#51]
Following a slack thread, if this repository is to contain all the constructs for CDK based deployment of all [eoAPI](https://github.com/developmentseed/eoAPI) services, we want to also have a construct and the FastAPI components for a vector application.

It would be pretty simple and quick :

```[tasklist]
### Tasks
- [ ] create a `/lib/tipg-api` folder
- [ ] take the construct from this [chunk of eoapi python code](https://github.com/developmentseed/eoAPI/blob/cad43784773dd3241602961e40567c24c40595ed/infrastructure/aws/cdk/app.py#L358C1-L399C55), convert it to TS and put it in the folder
- [ ] take the fastAPI components from this chunk of eoapi python code and put them in a `runtime` subfolder, that is going to be referenced by the TS construct
```
